# Nodejs Base image
FROM node:12.2.0-alpine
WORKDIR /app
#ENV PATH /app/node_modules/.bin:$PATH
# install and app dependencies
COPY package.json /app/package.json
RUN npm install -g npm@latest
RUN npm install -g @angular/cli
# add app
COPY . /app
# start app
CMD ng serve --sourceMap=false --host 0.0.0.0 --disable-host-check
